/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
import java.util.*;

class Main{
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Sum even or odds terms in the Fibonacci sequence?");
        String str = sc.nextLine();
        System.out.println("What number should the summed terms not exceed?");        
        int max = sc.nextInt();
        System.out.println((str.equals("odd")) ? fibonacciSum(max, true) : fibonacciSum(max, false));
        sc.close();
    }
    private static int fibonacciSum(int max, boolean isOdd){
        if(max < 3)
            return max;
        int fib1 = 1, fib2 = 1, fibonacci = 1, sum = 0;
        while(fibonacci <= max){
            if(isOdd && fibonacci % 2 == 1)
                sum += fibonacci;
            else
                sum += fibonacci;
            fibonacci = fib1 + fib2;        
            fib1 = fib2;
            fib2 = fibonacci;
        }
        return sum;
    }
}